### ISSUE TITLE
OpenAPI Cookie Extension?

### ISSUE THREAD

**Issue by HugoNikanor** [HugoNikanor/yapigen#3]
### The problem

OpenAPI says nothing about how response cookie are managed, meaning that they are simply added as all other headers

```yaml
response:
  headers:
    Set-Cookie: ...
```

This is sub-optimal, since the programmer then manually needs to keep track of which cookies to set, and with what values.

### A solution
Introduce an extension for specifying response cookies. Something like

```yaml
response:
  cookies:
    <cookie-name>:
      schema: <json-schema>
      description: <plain text description of the cookie>
      max-age: <...>
      ...
```

Exact format is yet to be determined, but should probably mimic request cookies (meaning parameter syntax), but with fields for all cookie parameters (`schema` (and possibly `content`) would be for the primary payload.
